name: console
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  csv: ^6.0.0
  intl: ^0.18.0
  http: ^1.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/
